(function() {var implementors = {};
implementors["pallet_contract_operator"] = [{"text":"impl&lt;T:&nbsp;Copy + Trait&gt; Copy for Module&lt;T&gt;","synthetic":false,"types":[]}];
implementors["pallet_custom_signatures"] = [{"text":"impl&lt;T:&nbsp;Copy + Trait&gt; Copy for Module&lt;T&gt;","synthetic":false,"types":[]}];
implementors["pallet_dapps_staking"] = [{"text":"impl&lt;T:&nbsp;Copy + Trait&gt; Copy for Module&lt;T&gt;","synthetic":false,"types":[]}];
implementors["pallet_operator_trading"] = [{"text":"impl&lt;T:&nbsp;Copy + Trait&gt; Copy for Module&lt;T&gt;","synthetic":false,"types":[]}];
implementors["pallet_ovm"] = [{"text":"impl&lt;T:&nbsp;Copy + Trait&gt; Copy for Module&lt;T&gt;","synthetic":false,"types":[]}];
implementors["pallet_plasm_lockdrop"] = [{"text":"impl&lt;T:&nbsp;Copy + Trait&gt; Copy for Module&lt;T&gt;","synthetic":false,"types":[]}];
implementors["pallet_plasm_rewards"] = [{"text":"impl Copy for Releases","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Copy + Trait&gt; Copy for Module&lt;T&gt;","synthetic":false,"types":[]}];
implementors["pallet_plasm_validator"] = [{"text":"impl&lt;T:&nbsp;Copy + Trait&gt; Copy for Module&lt;T&gt;","synthetic":false,"types":[]}];
implementors["pallet_plasma"] = [{"text":"impl&lt;T:&nbsp;Copy + Trait&gt; Copy for Module&lt;T&gt;","synthetic":false,"types":[]}];
implementors["plasm_runtime"] = [{"text":"impl Copy for Runtime","synthetic":false,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()