
// This file is part of Astar.

// Copyright (C) Stake Technologies Pte.Ltd.
// SPDX-License-Identifier: GPL-3.0-or-later

// Astar is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// Astar is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with Astar. If not, see <http://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_dapp_staking`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-02-02, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `gh-runner-01-ovh`, CPU: `Intel(R) Xeon(R) E-2236 CPU @ 3.40GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=./target/release/wbuild/astar-runtime/astar_runtime.compact.compressed.wasm
// --steps=50
// --repeat=20
// --pallet=pallet_dapp_staking
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./benchmark-results/astar/runtime/dapp_staking_weights.rs
// --template=./scripts/templates/runtime-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_dapp_staking`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_dapp_staking::WeightInfo for SubstrateWeight<T> {
	fn maintenance_mode() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_461_000 picoseconds.
		Weight::from_parts(8_677_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn register() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 16_555_000 picoseconds.
		Weight::from_parts(16_964_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn set_dapp_reward_beneficiary() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `97`
		//  Estimated: `0`
		// Minimum execution time: 14_462_000 picoseconds.
		Weight::from_parts(14_727_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn set_dapp_owner() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `97`
		//  Estimated: `0`
		// Minimum execution time: 14_304_000 picoseconds.
		Weight::from_parts(14_657_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn unregister() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `97`
		//  Estimated: `0`
		// Minimum execution time: 20_132_000 picoseconds.
		Weight::from_parts(20_603_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn lock_new_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `138`
		//  Estimated: `0`
		// Minimum execution time: 38_289_000 picoseconds.
		Weight::from_parts(38_691_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn lock_existing_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `158`
		//  Estimated: `0`
		// Minimum execution time: 38_869_000 picoseconds.
		Weight::from_parts(39_802_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn unlock() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `158`
		//  Estimated: `0`
		// Minimum execution time: 35_328_000 picoseconds.
		Weight::from_parts(35_790_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `x` is `[0, 16]`.
	fn claim_unlocked(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `190`
		//  Estimated: `0`
		// Minimum execution time: 38_313_000 picoseconds.
		Weight::from_parts(40_691_916, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 5_927
			.saturating_add(Weight::from_parts(101_758, 0).saturating_mul(x.into()))
	}
	fn relock_unlocking() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `200`
		//  Estimated: `0`
		// Minimum execution time: 35_715_000 picoseconds.
		Weight::from_parts(36_117_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `274`
		//  Estimated: `0`
		// Minimum execution time: 53_482_000 picoseconds.
		Weight::from_parts(54_756_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `459`
		//  Estimated: `0`
		// Minimum execution time: 58_638_000 picoseconds.
		Weight::from_parts(59_292_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `x` is `[1, 16]`.
	fn claim_staker_rewards_past_period(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `541`
		//  Estimated: `0`
		// Minimum execution time: 57_353_000 picoseconds.
		Weight::from_parts(56_809_462, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 5_135
			.saturating_add(Weight::from_parts(1_956_816, 0).saturating_mul(x.into()))
	}
	/// The range of component `x` is `[1, 16]`.
	fn claim_staker_rewards_ongoing_period(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `519`
		//  Estimated: `0`
		// Minimum execution time: 54_268_000 picoseconds.
		Weight::from_parts(53_207_081, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 7_050
			.saturating_add(Weight::from_parts(2_073_433, 0).saturating_mul(x.into()))
	}
	fn claim_bonus_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `275`
		//  Estimated: `0`
		// Minimum execution time: 46_935_000 picoseconds.
		Weight::from_parts(47_437_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn claim_dapp_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `668`
		//  Estimated: `0`
		// Minimum execution time: 30_151_000 picoseconds.
		Weight::from_parts(30_749_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn unstake_from_unregistered() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `322`
		//  Estimated: `0`
		// Minimum execution time: 48_601_000 picoseconds.
		Weight::from_parts(49_205_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `x` is `[1, 16]`.
	fn cleanup_expired_entries(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `257 + x * (73 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 46_242_000 picoseconds.
		Weight::from_parts(43_292_594, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 13_352
			.saturating_add(Weight::from_parts(6_282_784, 0).saturating_mul(x.into()))
	}
	fn force() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 11_385_000 picoseconds.
		Weight::from_parts(11_569_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn move_stake_from_registered_source() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `553`
		//  Estimated: `0`
		// Minimum execution time: 91_389_000 picoseconds.
		Weight::from_parts(92_244_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn move_stake_unregistered_source() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `419`
		//  Estimated: `0`
		// Minimum execution time: 82_041_000 picoseconds.
		Weight::from_parts(83_143_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn on_initialize_voting_to_build_and_earn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `225`
		//  Estimated: `0`
		// Minimum execution time: 25_935_000 picoseconds.
		Weight::from_parts(26_354_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn on_initialize_build_and_earn_to_voting() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `791`
		//  Estimated: `0`
		// Minimum execution time: 48_127_000 picoseconds.
		Weight::from_parts(48_815_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn on_initialize_build_and_earn_to_build_and_earn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `277`
		//  Estimated: `0`
		// Minimum execution time: 29_870_000 picoseconds.
		Weight::from_parts(30_278_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// The range of component `x` is `[0, 16]`.
	fn dapp_tier_assignment(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `218 + x * (33 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 11_764_000 picoseconds.
		Weight::from_parts(15_737_959, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 15_337
			.saturating_add(Weight::from_parts(3_019_595, 0).saturating_mul(x.into()))
	}
	fn on_idle_cleanup() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `293`
		//  Estimated: `0`
		// Minimum execution time: 10_067_000 picoseconds.
		Weight::from_parts(10_287_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn set_static_tier_params() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 11_443_000 picoseconds.
		Weight::from_parts(11_654_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
}
